/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockContractWithCall__factory } from "./MockContractWithCall__factory";
export { MockWithCallInterface__factory } from "./MockWithCallInterface__factory";
