/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockContractWithCall } from "./MockContractWithCall";
export type { MockWithCallInterface } from "./MockWithCallInterface";
